### ISSUE TITLE
 Запланировать связку OS+54.3 для VMWare

### ISSUE THREAD

**Issue by Iv-Alex** [mpk-it/Administration#60]
- [x] provide FC between 16 and work room
- [x] chek FC cards on servers - 54.3, blue basket and open space
- [x] copy system 54.3 throught disk2vhd
- [x] convert vm from generation 1 to generation 2 
- [x] [virtualization image 54.3 srv to 38 srv](https://github.com/mpk-it/Administration/issues/140)
- [x] [replace base from 54.3 to 139 srv](https://github.com/mpk-it/Administration/issues/115)
- [x] [replace base from 54.3 to  the 138 srv](https://github.com/mpk-it/Administration/issues/139)
